import { colors } from './theme';

export default {
  light: {
    text: colors.light.onSurface,
    background: colors.light.background,
    tint: colors.light.primary,
    tabIconDefault: colors.neutral[400],
    tabIconSelected: colors.light.primary,
    surface: colors.light.surface,
    surfaceVariant: colors.light.surfaceVariant,
    onSurface: colors.light.onSurface,
    onSurfaceVariant: colors.light.onSurfaceVariant,
    primary: colors.light.primary,
    onPrimary: colors.light.onPrimary,
    primaryContainer: colors.light.primaryContainer,
    onPrimaryContainer: colors.light.onPrimaryContainer,
    secondary: colors.light.secondary,
    onSecondary: colors.light.onSecondary,
    secondaryContainer: colors.light.secondaryContainer,
    onSecondaryContainer: colors.light.onSecondaryContainer,
    tertiary: colors.light.tertiary,
    onTertiary: colors.light.onTertiary,
    tertiaryContainer: colors.light.tertiaryContainer,
    onTertiaryContainer: colors.light.onTertiaryContainer,
    tertiaryFixed: colors.light.tertiaryFixed,
    onTertiaryFixedVariant: colors.light.onTertiaryFixedVariant,
    surfaceContainerLow: colors.light.surfaceContainerLow,
    surfaceContainerLowest: colors.light.surfaceContainerLowest,
    surfaceContainerHighest: colors.light.surfaceContainerHighest,
    outline: colors.light.outline,
    outlineVariant: colors.light.outlineVariant,
    error: colors.semantic.error,
    success: colors.semantic.success,
  },
  dark: {
    text: colors.dark.onSurface,
    background: colors.dark.background,
    tint: colors.dark.primary,
    tabIconDefault: colors.neutral[500],
    tabIconSelected: colors.dark.primary,
    surface: colors.dark.surface,
    surfaceVariant: colors.dark.surfaceVariant,
    onSurface: colors.dark.onSurface,
    onSurfaceVariant: colors.dark.onSurfaceVariant,
    primary: colors.dark.primary,
    onPrimary: colors.dark.onPrimary,
    primaryContainer: colors.dark.primaryContainer,
    onPrimaryContainer: colors.dark.onPrimaryContainer,
    secondary: colors.dark.secondary,
    onSecondary: colors.dark.onSecondary,
    secondaryContainer: colors.dark.secondaryContainer,
    onSecondaryContainer: colors.dark.onSecondaryContainer,
    tertiary: colors.dark.tertiary,
    onTertiary: colors.dark.onTertiary,
    tertiaryContainer: colors.dark.tertiaryContainer,
    onTertiaryContainer: colors.dark.onTertiaryContainer,
    tertiaryFixed: colors.dark.tertiaryFixed,
    onTertiaryFixedVariant: colors.dark.onTertiaryFixedVariant,
    surfaceContainerLow: colors.dark.surfaceContainerLow,
    surfaceContainerLowest: colors.dark.surfaceContainerLowest,
    surfaceContainerHighest: colors.dark.surfaceContainerHighest,
    outline: colors.dark.outline,
    outlineVariant: colors.dark.outlineVariant,
    error: colors.semantic.error,
    success: colors.semantic.success,
  },
};

